using MetadataExtractor.Formats.Jfif;

namespace Picture_Audit_Community.ClassItems
{
    public class MetaReport
    {
        //META DATA TABLES USE THEM TO READ AND WRITE FROM THE PHOTOS METADATA
        public List<string> StringReport = new List<string>();
        public string ReportName { get; set; }
        private static string repval { get; set; }
        public List<MetaData> Meta_Data { get; set; } = new List<MetaData>();

        private static readonly List<AuditRule> Rules = new List<AuditRule>
    {
        //Rule set: see all items in the array in a meta table inside the image and if all are read then create the caption
        new AuditRule(new[] { "Pixels Per Unit X", "Pixels Per Unit Y" }, "Image Manipulated"),
        new AuditRule(new[] { "Exif IFD0: Model" }, "Camera Model:",true),
       new AuditRule(new[] { "Exif IFD0", "Exif SubIFD" }, "Proffessional Camera Data"),
        new AuditRule(new[] { "crs:ProcessVersion", "crs:Exposure2012" }, "Image Processed"),
        new AuditRule(new[] { "CreatorToolAdobe Photoshop"}, "Photoshop"),
        new AuditRule(new[] { "PNG-sRGB: sRGB Rendering IntentPerceptual", "PNG-gAMA: Image Gamma0,455" }, "ScreenShot (Windows)"),
        new AuditRule(new[] { "OpenAI" }, "Confirmed AI Origin: ChatGPT/DALL-E"),
        new AuditRule(new[] { "gpt" }, "Confirmed AI Origin: ChatGPT/DALL-E"),
        new AuditRule(new[] { "JFIF: Y Resolution1 dot","JFIF: X Resolution1 dot" }, "Programmatic Code or AI Generated Image"),//this does not make sense so it has been inside a tampering software or the image was generated by AI
        new AuditRule(new[] { "5184", "3456", "Progressive" },"Professional DSLR source detected, but Exif data has been stripped for web distribution."),
    };
 


        public void CreateReport() {
            StringReport.Clear();

            foreach (var rule in Rules)
            {
                if (ValidateRule(rule)) { StringReport.Add(rule.Footnote + repval); }
        
            }
            //remove dublicates
            var uniqueItems = StringReport.Distinct().ToList();
            StringReport.Clear();
            foreach (var item in uniqueItems)
            {
                StringReport.Add(item);
            }

        }

        private bool ValidateRule(AuditRule rule)
        {
            repval = "";
            // Check every required word in the current rule
            foreach (string word in rule.Requirements)
            {
                bool foundThisWord = false;

               
                foreach (MetaData meta in Meta_Data)
                {
                    if (SearchForCaption(word,meta, rule.AddVal))
                    {
                        foundThisWord = true;
                        break; 
                    }
                }
                if (!foundThisWord)
                {
                    return false;
                }
            }

           
            return true;
        }

        public bool SearchForCaption(string caption, MetaData Metatags,bool captionval)
        {

            foreach (MetaTag Tag in Metatags.Tags)
            {
                string combine = Tag.TagName + Tag.TagValue;
                if (combine.Contains(caption))
                {
                    if (captionval) { repval = Tag.TagValue; }
                   
                    return true;
                }
            }
            return false;
        }


    }

    public class MetaData
    {
        public string Name { get; set; }
        public List<MetaTag> Tags { get; set; } = new List<MetaTag>();
       
        public void AddCaption()
        {
            foreach (MetaTag tag in Tags)
            {
                string Tname = tag.GetCaptionIdentifier();
                // Check against the actual string returned by the CategoryMap
                if (!string.IsNullOrEmpty(Tname) && Tname != "Uncategorized Metadata")
                {
                    Name = Tname;
                    return;
                }
            }
            if (string.IsNullOrEmpty(Name)) Name = "General Metadata";
        }
    }



public class MetaTag {
  
        private static readonly Dictionary<string, string> CategoryMap = new Dictionary<string, string>
    {
            { "ihdr", "IHDR Structural Attributes" },
            { "type name", "MIME Type Verification" },
            { "jpeg", "JPEG Compression & Components" },
            { "exif ifd0", "Camera Hardware & Software" },
            { "exif subifd", "Exif Shooting Parameters" },
            { "exif thumbnail", "Embedded Thumbnail Metrics" },
            { "xmp", "Post-Processing & Lens Calibration" },
            { "icc profile", "ICC Color Profile Specifications" },
            { "photoshop", "Photoshop Resource Blocks" },
            { "iptc", "IPTC Content Standards" },
            { "adobe jpeg", "Adobe JPEG DCT Encoding" },
            { "huffman", "Entropy Coding (Huffman)" },
            { "ai_detection", "Authenticity & AI Provenance" },
            { "file name", "System Storage Manifest" },
            { "file size", "System Storage Manifest" },
            { "file modified", "System Storage Manifest" },
            { "gps", "Camera GPS Settings" },
            { "makernote", "Camera Maker Note" },
            { "picturecontrol", "Picture Control Settings" },
            { "interoperability", "interoperability Settings" },
            { "jfif","JFIF settings"}
    };
        public string TagName { get; set; }
        public string TagValue { get; set; }

        public MetaTag()
        {
            this.TagName = "";
            this.TagValue = "";
        }

        public MetaTag(string Name, string Value)
        {
            this.TagName = Name;
            this.TagValue = Value;
        }


        public string GetCaptionIdentifier()
        {
            if (string.IsNullOrEmpty(this.TagName)) return "Unknown Category";

            string lowerTag = this.TagName.ToLower();

            // Find the first key that is contained within the TagName
            var match = CategoryMap.FirstOrDefault(kvp => lowerTag.Contains(kvp.Key));

            // Return the mapped value if found, otherwise a default string
            return match.Value ?? "Uncategorized Metadata";
        }




    }




    public class AuditRule {

        public bool AddVal { get; set; } 
        public string[]  Requirements { get; set; }
        public string Footnote { get; set; }
        public AuditRule(string[] requirements, string note)
        {
            Requirements = requirements;
            Footnote = note;
            AddVal = false;
        }

        public AuditRule(string[] requirements, string note,bool val)
        {
            Requirements = requirements;
            Footnote = note;
            AddVal= val;
        }


    }


}
